require("mini.comment").setup()
require("mini.diff").setup({ source = require("mini.diff").gen_source.git({ index = false }) })
require("mini.extra").setup()
require("mini.files").setup()
require("mini.icons").setup()
require("mini.pairs").setup()
require("mini.pick").setup()
require("mini.surround").setup()
