"$schema" = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"
console_title_template = '{{ .Shell }} in {{ .Folder }}'
version = 3
final_space = true

[transient_prompt]
template = '❯ '
background = 'transparent'
foreground_templates = [
  '{{if gt .Code 0}}red{{end}}',
  '{{if eq .Code 0}}magenta{{end}}',
]

[[blocks]]
type = 'prompt'
alignment = 'left'
newline = true

[[blocks.segments]]
leading_diamond = ''
trailing_diamond = ''
template = '󱁇 {{ .UserName }} '
foreground = '#eeeeee'
background = '#5900b3'
type = 'session'
style = 'diamond'

[blocks.segments.properties]
cache_duration = 'none'

[[blocks.segments]]
template = ' {{ if .Venv }} {{ .Venv }}{{ end }} '
foreground = '#eeeeee'
background = '#e68a00'
powerline_symbol = ''
type = 'python'
style = 'powerline'

[[blocks.segments]]
template = ' {{ .Path }} '
foreground = '#eeeeee'
powerline_symbol = ''
background = '#7a00e6'
type = 'path'
style = 'powerline'

[blocks.segments.properties]
cache_duration = 'none'
folder_icon = ' '
folder_separator_icon = '  '
home_icon = ''
style = 'agnoster'

[[blocks.segments]]
template = '  {{ .HEAD }}{{ if .Staging.Changed }}<#eeeeee>  {{ .Staging.String }}</>{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }} '
foreground = '#eeeeee'
powerline_symbol = ''
background = '#794dff'
type = 'git'
style = 'powerline'

[blocks.segments.properties]
branch_icon = ' '
cache_duration = 'none'
cherry_pick_icon = ' '
commit_icon = ' '
fetch_status = true
fetch_upstream_icon = true
merge_icon = ' '
no_commits_icon = ' '
rebase_icon = ' '
revert_icon = ' '
tag_icon = ' '

[[blocks]]
type = 'prompt'
alignment = 'left'
newline = true

[[blocks.segments]]
template = ' ❯'
foreground = 'magenta'
type = 'text'
style = 'plain'

[blocks.segments.properties]
cache_duration = 'none'
