"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
($directory)\
$nodejs\
$bun\
$conda\
$python\
$git_branch\
$git_status\
\n$character\
"""

add_newline = true

# color and style settings
palette = "catppuccin_mocha"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[character]
success_symbol = "[ ❯](fg:mauve)"
error_symbol = "[ !](fg:red)"

[username]
style_root = 'red bold'
format = '[](fg:#5f00d7)[󱁇 ](bg:#5f00d7 fg:#eeeeee)[$user ](bg:#5f00d7 fg:#eeeeee)[](fg:#5f00d7)'
show_always = true

[directory]
format = "[](bg:#8700ff fg:base)[$path](bg:#8700ff)"
truncation_length = 5
style = "fg:flamingo"
before_repo_root_style = "fg:mauve"
truncate_to_repo = false
read_only = "  "
home_symbol = "  "

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
format = "=> [$symbol$branch]($style) "
style = "bold fg:teal"
symbol = " "

[git_status]
modified = "●$count"
staged = "✚$count"
renamed = "➜$count"
untracked = "?$count"
deleted = "✖$count"
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'
style = "yellow bold"

[python]
disabled = false
symbol = " "
version_format = "${raw}"
style = "yellow bold"

[conda]
symbol = " "

[bun]
disabled = false
version_format = "${raw}"
symbol = " "
style = "bold text"

[nodejs]
symbol = " "
